### ISSUE TITLE
isconcrete not defined

### ISSUE THREAD

**Issue by baggepinnen** [JuliaGraphics/ColorTypes.jl#100]
On both master and latest tagged release:
```
julia> using ColorTypes
INFO: Precompiling module ColorTypes.
ERROR: LoadError: UndefVarError: isconcrete not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /local/home/fredrikb/.julia/v0.6/ColorTypes/src/ColorTypes.jl, in expression starting on line 9
ERROR: Failed to precompile ColorTypes to /local/home/fredrikb/.julia/lib/v0.6/ColorTypes.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398

julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by Evizero** [comment]
I can't reproduce this on 0.6. 

what does the following say:

```julia
Pkg.status("ColorTypes")
Pkg.status("Compat")
```

**Comment by baggepinnen** [comment]
I have tried checking out master on both Compat and ColorTypes but the problem persists
```julia
julia> Pkg.status("ColorTypes")
 - ColorTypes                    0.6.4              master
julia> Pkg.status("Compat")
 - Compat                        0.32.0             master
```

**Comment by Evizero** [comment]
`isconcrete` seems to have been introduced to ColorTypes with https://github.com/JuliaGraphics/ColorTypes.jl/commit/ee160a9a46a702634a7e6dc2f99ed1e713cdd80c . Maybe @yuyichao has an idea what your problem could be? I don't experience any issues.

**Comment by timholy** [comment]
Update your packages? And make sure you're running the latest Compat.

**Comment by yuyichao** [comment]
Most likely a local setup issue. The backtrace suggests that you don't actually have an up to date Compat.jl. Possible cause includes having something in `LOAD_PATH`, having a dirty `Compat`, having `Compat` in `userimg.jl` etc.

**Comment by baggepinnen** [comment]
You're right @yuyichao , a package in userimage was using Compat. Thanks, I would have never figured that out myself!

**Comment by innerlee** [comment]
@baggepinnen Could you share your solution here? (I know this is not discource. But it is the first and the only exact entry when googled.)

**Comment by baggepinnen** [comment]
I recompiled the system image, in my case the commands were
```julia
include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))
build_sysimg(default_sysimg_path(), "native", "userimage.jl", force=true)
```

**Comment by yuyichao** [comment]
@baggepinnen Do **NOT** do it unless you are also compiling your own sysimg with a `userimg.jl`.

**Comment by baggepinnen** [comment]
What is the difference between running the command `build_sysimg` and compiling my own sysimg?

**Comment by yuyichao** [comment]
None. I just mean that the google search that led @innerlee here is unlikely userimg related in which case building the sysimg is most likely not the solution.

**Comment by timholy** [comment]
@innerlee, the first thing to check is `Pkg.status("Compat")`. If it says "dirty" or anything less than the version in the [ColorTypes REQUIRE file](https://github.com/JuliaGraphics/ColorTypes.jl/blob/master/REQUIRE), then you need to update your packages and/or clear out any modifications you've made locally to Compat and then update.

**Comment by innerlee** [comment]
The Compat status looks good. I also tried deleted `~/.julia/v0.6/Compat` and `~/.julia/.cache/Compat`, and then reinstalled Compat.
```julia
julia> Pkg.status("Compat")
 - Compat                        0.32.0

julia> using Plots
INFO: Precompiling module PlotUtils.
ERROR: LoadError: UndefVarError: isconcrete not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] anonymous at ./<missing>:2
while loading /home/lizz/.julia/v0.6/ColorTypes/src/ColorTypes.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile ColorTypes to /home/lizz/.julia/lib/v0.6/ColorTypes.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/lizz/.julia/v0.6/Colors/src/Colors.jl, in expression starting on line 5
ERROR: LoadError: Failed to precompile Colors to /home/lizz/.julia/lib/v0.6/Colors.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/lizz/.julia/v0.6/PlotUtils/src/PlotUtils.jl, in expression starting on line 7
ERROR: LoadError: Failed to precompile PlotUtils to /home/lizz/.julia/lib/v0.6/PlotUtils.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] eval(::Module, ::Any) at ./boot.jl:235
 [6] _require(::Symbol) at ./loading.jl:483
 [7] require(::Symbol) at ./loading.jl:398
while loading /home/lizz/.julia/v0.6/Plots/src/Plots.jl, in expression starting on line 13

julia> versioninfo()
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by timholy** [comment]
What happens if you start a fresh Julia session and just type `Compat`? Here's what it does for me:
```julia
julia> Compat
ERROR: UndefVarError: Compat not defined
```
But if you get this instead:
```julia
julia> Compat
Compat
```
and you don't have anything in your `.juliarc.jl` file that would force the loading of Compat (you could start julia with `julia --startup-file=no` to be sure), then that means you've compiled a `userimg.jl` that loads Compat. So then you should indeed follow @baggepinnen's solution.

**Comment by innerlee** [comment]
Thanks for the diagnose instruction. You are right, I compiled `userimg.jl` for loading `OhMyREPL` a while ago and have then completely forgot about it. Everything is okay on another machine so thanks!
