### ISSUE TITLE
Implement RGB8 / RGB332

### ISSUE THREAD

**Issue by scls19fr** [JuliaGraphics/ColorTypes.jl#115]
Similar to #114 and following https://github.com/JuliaGraphics/Colors.jl/issues/332#issuecomment-447551891

Implementing RGB8 [8-bit colors](https://en.wikipedia.org/wiki/8-bit_color) which are generally represented as

```
7 6 5|4 3 2|1 0
-----|-----|---
R R R|G G G|B B
```

* 3 bits for **red** channel (8 values)
* 3 bits for **green** channel (8 values)
* 2 bits for **blue** channel (4 values)

might be considered

**Comment by scls19fr** [comment]
WIP:

```julia
import ColorTypes: blue, green, red
import Base: UInt8

"""
`RGB8` is Red-Green-Blue colorspace represented by one byte (8 bits).

7  6  5  4  3  2  1  0
R  R  R  G  G  G  B  B
"""
struct RGB8
    value::UInt8
end

function RGB8(r, g, b)
    RGB8(r << 5 + g << 2 + b)
end

UInt8(c::RGB8) = c.value

blue(c::RGB8) = c.value & 0x03
green(c::RGB8) = (c.value & 0x1c) >> 2
red(c::RGB8) = (c.value & 0xe0) >> 5

using Test
@testset "RGB8" begin
    c = RGB8(7, 7, 3)  # white
    @test red(c) == 7
    @test green(c) == 7
    @test blue(c) == 3
    @test UInt8(c) == 255

    c = RGB8(0, 0, 0)  # black
    @test UInt8(c) == 0

    c = RGB8(7, 0, 0)  # red
    @test UInt8(c) == 224

    c = RGB8(0, 7, 0)  # green
    @test UInt8(c) == 28

    c = RGB8(0, 0, 3)  # blue
    @test UInt8(c) == 3

end
```

I will submit a PR for `RGB8` after #116 being reviewed and fixed

**Comment by kimikage** [comment]
I think the name of `RGB8` is ambiguous.  (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/114#issuecomment-465434197)

Sometimes the RGB8 means the RGB888, i.e. `RGB24`.   
The thing that is more worrisome to me is the `RGB4` historically represents a 32-bit color.

**Comment by scls19fr** [comment]
Maybe we should consider naming it `RGB332`

**Comment by timholy** [comment]
Let's name this `RGB332` and change the name of `RGB4` to something else. What would you suggest @kimikage? Maybe `RGB32Last`? And `RGB1` goes to `RGB32First`?

**Comment by kimikage** [comment]
I'm sorry for the late reply.

Although I don't think `RGB1` and `RGB4` are great names, the two names have already _matured_.
So, I prefer to keep the status quo until a specific collision occurs.
If we have to change the names, how about `XRGB` and `RGBX` (or `XRGB32` and `RGBX32`)?
(See also: https://www.kernel.org/doc/html/latest/media/uapi/v4l/pixfmt-packed-rgb.html)

Anyway, I have absolutely no objection to `RGB332`.

**Comment by timholy** [comment]
I really like `XRGB` and `RGBX`. I think I will make that change (though as you say it's a bit painful).

WRT this proposal, #116 got close.

**Comment by kimikage** [comment]
see: https://github.com/JuliaGraphics/ColorTypes.jl/issues/114#issuecomment-805617915
