### ISSUE TITLE
getindex of RGBA

### ISSUE THREAD

**Issue by Datseris** [JuliaGraphics/ColorTypes.jl#117]
This should be something trivial:
```

julia> c = get_color(1)
RGBA{Float32}(0.24671534f0,0.28681165f0,0.53517556f0,1.0f0)

julia> ans[1:3]
ERROR: MethodError: no method matching getindex(::ColorTypes.RGBA{Float32}, ::UnitRange{Int64})
Stacktrace:
 [1] top-level scope at none:0

julia> c[1]
ERROR: MethodError: no method matching getindex(::ColorTypes.RGBA{Float32}, ::Int64)
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by SimonDanisch** [comment]
I've been wanting to have `getindex` for colors, but it was deliberately chosen to not implement it, since the order is not well defined (is c[1] the red channel or blue?) and colors are understood as scalars.
Alternatively, there are the functions `mapc`, `color`, `blue`, `red`, `green`, `alpha`.

**Comment by Datseris** [comment]
Thanks `blue`, `red`, `green` does exactly what I want. Should be documented as well though.

**Comment by Datseris** [comment]
Well, it _is_ documented. But for a front end user they have to search read me of some obscure low-level package.

**Comment by timholy** [comment]
I doubt anyone would object if you opened a PR to add them in a more visible place.
