### ISSUE TITLE
`gamutmax(LCHab)` disagrees with the Colors.jl usage

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#125]
The max saturation of `LCHab` is defined as `1` in ColorTypes.jl.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/0d5904e19b41227938274d325886dff221a8e8d7/src/operations.jl#L16-L17

However, in Colors.jl, the saturation comes from the `a` and `b` of `Lab` which are _mostly_ in [-100,100].
https://github.com/JuliaGraphics/Colors.jl/blob/657e265a4cccc9fc32584f7f3505611537bfc79d/src/conversions.jl#L575-L580

Therefore, for the sake of convenience,  `100` (or `128`) is better for the max saturation, though the actual gamut is not so simple. (See also: #84)

**Comment by timholy** [comment]
Another option is to remove support for ones without a clearly defined max/min?

**Comment by kimikage** [comment]
In the case of `LCHab`, the removal is probably OK, as no one has pointed this out.

However, few types have a clearly defined max/min, because the range of color space and the color gamut are based on different concepts.

BTW, I found this issue when I ran `rand(LCHab)`.
I think `gamutmax` and `gamutmin` are practical when and only when they are used with `rand()` as historically they are introduced for such a purpose.
Perhaps what we should remove might be the term “gamut” rather than the function.

**Comment by kimikage** [comment]
As mentioned above, I think that "color gamut" and `rand` should be separated.
Then, `rand` should be more comprehensive. For example, there is a problem with `TransparentColor`:
```julia
julia> rand(RGBA)
RGBA{Float64}(0.4054196785489861,0.5812337734513682,0.4739237429262706,0.35592317884458446)

julia> rand(Lab)
Lab{Float64}(49.35707185830977,54.78932461097497,-80.6404236285697)

julia> rand(LabA)
ERROR: MethodError: no method matching gamutmax(::Type{LabA{Float64}})
```

Although it is necessary to discuss whether `ColorTypes.jl` should specify the ranges (not gamuts) or not, it may be the duty of `ColorTypes.jl` to resolve the range of `AlphaColor` and `ColorAlpha`, given the range of `color_type`.

**Comment by kimikage** [comment]
BTW, `gamutmin`/`gamutmux` for YIQ are broken, too.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/9607b73d9c52469be61a9e2892ea3f504b175e60/src/operations.jl#L18-L19

```julia
correct_gamut(c::YIQ{T}) where {T} = YIQ{T}(clamp(c.y, zero(T), one(T)),
                                     clamp(c.i, convert(T,-0.5957), convert(T,0.5957)),
                                     clamp(c.q, convert(T,-0.5226), convert(T,0.5226)))
```
