### ISSUE TITLE
Hue range definition ([0,360)? or [0,360]?)

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#128]
[Readme.md](https://github.com/JuliaGraphics/ColorTypes.jl/blob/v0.8.0/README.md#hsv) says the range of hue is [0,360). However, the implementations in Colors.jl have not followed the rule.
Although it is common sense in numerical analysis, the `convert()` to color types which have the "float" hue, may output `360.0`.
```julia
julia> prevfloat(360.0) # display is OK
359.99999999999994

julia> convert(HSV, RGB(1,0,1e-16)).h
360.0
```
I have three options.
- Change the definition to [0,360]
- Add notes about the exceptional `360.0` without changing the definition
- Modify the implementations in Colors.jl to keep in [0,360)

Of course, users can generate `HSV(999, 0.0, 0.0)`, though. However, I don't think the range check in constructors really good now.

**Comment by timholy** [comment]
I'd support changing the README to `[0,360]`.

**Comment by kimikage** [comment]
FYI, Julia has been so kind as to explain the reason with examples.
https://docs.julialang.org/en/v1/base/math/#Base.mod

**Comment by kimikage** [comment]
The `normalize_hue` added to Colors.jl returns the hue in [0, 360]. I will mention in the documentation of Colors.jl the reason that "360" is included.
I will also modify the documents for ColorTypes.jl.

**Comment by kimikage** [comment]
BTW, I forgot to add `hue` and` chroma` to README.md. I will add them together with the fix for this issue.

**Comment by simonbyrne** [comment]
What about changing Hue to take values in the interval [-180,180]? That way the reduction can be done exactly via `rem(x,360,RoundNearest)` (from https://github.com/JuliaLang/julia/issues/36310).

**Comment by kimikage** [comment]
I think the hue errors are less of a concern in color/image applications.
```julia
julia> eps(360.0f0)
3.0517578f-5
```
I think we should follow the custom.
