### ISSUE TITLE
implement `Base.zero` and `Base.zeros` etc for color types like RGB, RGBA, RGB24 etc.

### ISSUE THREAD

**Issue by rafaqz** [JuliaGraphics/ColorTypes.jl#130]
Is there a reason these methods don't exist already?

**Comment by kimikage** [comment]
I think there are two reasons. First, `ColorTypes.jl` is "minimalistic" package and provides little operation interfaces. Secondly, the RGB color space is non-linear, and `RGB(0, 0, 0)` may not satisfy the property of the *additive identity* (i.e. zero).

Whatever the reason, [`ColorVectorSpace.jl`](https://github.com/JuliaGraphics/ColorVectorSpace.jl) provides mathematical operations including the `zero`.

If it is `zero` in terms of clearing bits, not `zero` in mathematical terms, the second reason can be ignored.

**Comment by rafaqz** [comment]
Ok thanks. I wasn't aware ColorVectorSpace.jl was that tightly coupled to ColorTypes that it is pirating the types in Base methods, but the readme does kinda make that clear :)
