### ISSUE TITLE
Adding `chroma()` and `hue()`

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#134]
What about adding `chroma()` and `hue()`?
```julia
"""
    chroma(c)

Returns the chroma of `c`, which is a `Lab`, `Luv` or their variants color.
!!! note
    The other color types (e.g. `RGB`, `HSV` or `YCbCr`) are not supported
    because their definitions of *chroma* are not clear. Colorfulness, chroma
    and saturation are defined as distinct aspects by the CIE.
"""
chroma(c::Union{Lab, DIN99, DIN99o, DIN99d}) = sqrt(c.a * c.a + c.b * c.b)
chroma(c::Luv) = sqrt(c.u * c.u + c.v * c.v)
chroma(c::Union{LCHab, LCHuv}) = c.c

"""
    hue(c)

Returns the hue of `c` in degrees. This function does not guarantee that the
return value ​​is in [0, 360].
"""
hue(c::Union{HSV, HSL, HSI, LCHab, LCHuv}) = c.h
hue(c::Union{Lab, DIN99, DIN99o, DIN99d}) = (h = atand(c.b, c.a); h < 0 ? h + 360 : h)
hue(c::Luv) = (h = atand(c.v, c.u); h < 0 ? h + 360 : h)
```

Although they are not so helpful in functionality, they can clean up the `Colors.jl` code. When we are considering issues like #128, it is good to gather trivial codes in one place. (FYI, the `hue()`s shown above may return `360.0`.)

In my initial plan, *the place* was in `Colors.jl` taking the package version dependencies into consideration. However, I think `ColorTypes.jl` is more appropriate *now*.

**Comment by timholy** [comment]
:+1:

**Comment by kimikage** [comment]
The point I am worried about is that when we export these functions (in particular `hue`), name collisions may occur. The different scopes will avoid breaking, but they may confuse the developers or linters.

Of course, we can choose not to export.

Which do you prefer, `sqrt(c.a * c.a + c.b * c.b)` or `sqrt(c.a^2 + c.b^2)`? :smile:

**Comment by timholy** [comment]
Nah, I'm not worried. If any package should own the names `chroma` and `hue`, it's this one.

WRT the format, you're probably aware they are the same thanks to `Base.literal_pow`? But Colors/ColorTypes was written before that existed, so there may be some legacy code.

**Comment by kimikage** [comment]
Oh, I forgot `AlphaColor` and `ColorAlpha`.

**Comment by kimikage** [comment]
They were added by PR #135.
