### ISSUE TITLE
support `ones(::Type{<:AbstractGray}, sz)`

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/ColorTypes.jl#137]
Since `one(Gray)` is deprecated, it would be convenient that the following kind of usage isn't affected:

```julia
julia> ones(Gray{N0f8}, 4, 4)
┌ Warning: one(Gray{Normed{UInt8,8}}) will soon switch to returning 1; you might need to switch to `oneunit`
│   caller = ones at array.jl:462 [inlined]
└ @ Core .\array.jl:462
4×4 Array{Gray{N0f8},2} with eltype Gray{Normed{UInt8,8}}:
...
```

It is "easier" to read than `Gray.(ones(N0f8, 4, 4))`.

P.S., this has the same issue in https://github.com/JuliaGraphics/Colors.jl/issues/369 if we don't specify the concrete storage type.

```julia
julia> ones(Gray, 4, 4)
4×4 Array{Gray{Any},2} with eltype Gray:
```

**Comment by kimikage** [comment]
cf. #130

**Comment by johnnychen94** [comment]
Perhaps it's better to move this issue to `ColorVectorSpace`

**Comment by johnnychen94** [comment]
cc @ianshmean

Just saw your post in slack

**Comment by kimikage** [comment]
Should we include a solution for this issue in ColorType.js v0.10? (cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/160#issuecomment-592506240)

cc @johnnychen94

**Comment by johnnychen94** [comment]
It looks like ColorTypes is the right place. I'll see if I can manage it tomorrow if you don't have plans on covering it. (My recent focus has shifted to Flux and deep learning things 😄 )

**Comment by kimikage** [comment]
This was supported by PR #243. (I thought I had closed this.:sweat_smile:)
```julia
julia> ones(Gray{N0f8}, 4, 4)
4×4 Matrix{Gray{N0f8}}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> ones(Gray, 4, 4) # non-concrete type
4×4 Matrix{Gray}:
 Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)
 Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)
 Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)
 Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)  Gray{N0f8}(1.0)
```
