### ISSUE TITLE
Adding/migration of gray-to-rgb conversion methods

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#144]
ColorTypes.jl has the special real-to-rgb conversion methods.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/81682158aec852502755ca0d3b943d2f34a71678/src/conversions.jl#L43-L44
In addition, ColorTypes.jl assumes that real numbers are gray-like and vice versa.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/81682158aec852502755ca0d3b943d2f34a71678/src/conversions.jl#L49-L51
Therefore, ColorTypes.jl "substantially" defines the gray-to-rgb conversions. However, ColorTypes.jl does not actually provide the gray-to-rgb conversion methods.
```julia
julia> using ColorTypes

julia> convert(RGB24, 0.8)
RGB24(0.8N0f8,0.8N0f8,0.8N0f8)

julia> convert(RGB24, Gray24(0.8))
ERROR: No conversion of Gray24(0.8N0f8) to RGB24 has been defined

julia> convert(RGB, Gray(0.8))
ERROR: No conversion of Gray{Float64}(0.8) to RGB{Float64} has been defined

julia> using Colors

julia> convert(RGB, Gray(0.8))
RGB{Float64}(0.8,0.8,0.8)
```

I think the rgb-to-gray conversion methods should be in Colors.jl, but the gray-to-rgb conversion methods may be in ColorTypes.jl.
The reason I think so is that it is time to do https://github.com/JuliaGraphics/Colors.jl/issues/273#issuecomment-557839812. :rocket:

**Edit:**
Of course, leaving `promotion_rule`s in Colors.jl is another option. By using only ColorTypes.jl and not using Colors.jl, we can define different promotion rules from Colors.jl. However, in practice, it is not a good thing.

**Comment by kimikage** [comment]
And I want to apply #129 along with this. (I am looking for a more elegant way.)

**Comment by timholy** [comment]
There's a certain consistency to this if we also support https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/119: `0.2*rgb == RGB(0.2)*rgb`. I've formerly thought the left hand side makes sense and the rhs does not, but I'm beginning to change my thinking.

**Comment by kimikage** [comment]
As you know, "convertible" and "equivalent" are different things. 
I believe `RGB(0.2,0.2,0.2) == Gray(0.2)` must return `false`. (To be honest, I'm not comfortable with treating `Gray` like a dimensionless number.)
