### ISSUE TITLE
Improve type hierarchy chart

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#145]
I want to improve the type hierarchy chart, *just for a change of pace*. :smile:

There are no major problems with the current chart, but I'm concerned about:
- `RGB24` is absent, even though it is one of the grounds for the need for `AbstractRGB`.
- `AbstractGray` is absent, although it is an alias for `Color{T,1}`
- `LMS` is a somewhat minor type.
- The left labels "Abstract types"/"Concrete types" are difficult to read on a dark background.
- The background for the `Color{T,N}`s is dull, even though `Color` is more primitive than `TransparentColor`

WIP:
![types](https://user-images.githubusercontent.com/12679384/72075156-8886af00-3336-11ea-8777-d9529e4f7706.png)

I'm going to add `Color{T,3}` and `Color{T,1}`. (They are not a "subtype" of `Color{T,N}`, though.) I intend to express the "lexical" hierarchy by connections (i.e. edges) and the semantic hierarchy by positions.

**Comment by timholy** [comment]
Sounds good. Not sure I understand what you mean about 

> I'm going to add Color{T,3} and Color{T,1}

but I'm optimistic it will make sense once I see the result.

**Comment by kimikage** [comment]
One reason I decided to change the chart is the some type aliases are somewhat strange. (However, I soon realized that it was difficult to organize them into a single diagram. :sweat_smile:)
I just thought they were weird, but I don't think they should be fixed.

`AbstractGray` and `Color3` are defined as
https://github.com/JuliaGraphics/ColorTypes.jl/blob/81682158aec852502755ca0d3b943d2f34a71678/src/types.jl#L68-L69
`Color{T,1}` represents the opaque "monotone" colors. Some old monotone CRT displays show green or amber screens, not "gray". :smile:

ImageCore.jl defines `ColorN{T}`s, but they are not consistent with `Color3{T}`.
```julia
Color1{T} = Colorant{T,1}
Color2{T} = Colorant{T,2}
Color4{T} = Colorant{T,4}
```
Of course, `TransparentColor{C,T,3}` is almost never used, so there is no problem. However, for this reason, I have decided that `ColorN{T}`s should not be moved to ColorTypes.jl (cf. PR #146 ).

**Comment by kimikage** [comment]
This is also off-topic, but ColorVectorSpace,jl defines some aliases with a TODO comment.
```julia
# TODO: we get rid of these definitions or move them to ColorTypes.jl
TransparentRGBFloat{C<:AbstractRGB,T<:AbstractFloat} = TransparentColor{C,T,4}
TransparentGrayFloat{C<:AbstractGray,T<:AbstractFloat} = TransparentColor{C,T,2}
TransparentRGBNormed{C<:AbstractRGB,T<:Normed} = TransparentColor{C,T,4}
TransparentGrayNormed{C<:AbstractGray,T<:Normed} = TransparentColor{C,T,2}
```
https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/dada616ecd2e1c500f06aba288fb24f9201fe28d/src/ColorVectorSpace.jl#L33-L37

Personally, I don't want to include them in ColorTypes.jl because I don't see the benefit of including the names of  element types in aliases.

**Comment by kimikage** [comment]
I'm sorry this is late.
![types](https://user-images.githubusercontent.com/12679384/74609123-3f423000-512a-11ea-97f6-73ab611c63c6.png)

**Comment by timholy** [comment]
I like it! Nice work!

**Comment by waldyrious** [comment]
Just a minor suggestion: how about changing the line between `AbstractGray{T}` and `Color{T,1}` to have a double-stroke? That would make it more obvious that it's an intentional difference from the other lines, rather than a possible overlook (i.e. missing arrowhead). In addition, a double-stroked line would resemble an equal sign, which would reinforce the type alias meaning.

**Comment by kimikage** [comment]
If there is no objection, I will `push -f` this version.:smile:

![types](https://user-images.githubusercontent.com/12679384/74734688-66b40c80-5292-11ea-8f75-27e6df5574fc.png)

**Comment by timholy** [comment]
It's onto #165, right? In my mind it's always OK to force-push to branches.

**Comment by kimikage** [comment]
If issue #129 (PR #164) needs time for discussion, let's merge PR #165 first to reduce the number of issue reports.
