### ISSUE TITLE
Organizing test cases

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#149]
Although it is what probably many people, including me, are pretending not to see, we should organize the test cases.

I'm going to add dozens of tests to merge PR #147. I can't stand the number of lines in a single file any more. In addition, the tests which I'm going to add, should have been included in either of tests for ColorTypes.jl or Colors.jl . However, I did not notice the absence until now. It is difficult to confirm the completeness of the current ColorTypes.jl's tests.

I want to split the tests into multiple files, and add `@testset`. In order to prevent the loss due to the move, I'll make commits in small units. This is a bit time-consuming, i.e. I can't merge PR #147 right away. If anyone do other work in ColorTypes.jl or Colors.jl, be aware of the consistency between them.

**Comment by kimikage** [comment]
WIP: https://github.com/JuliaGraphics/ColorTypes.jl/compare/master...kimikage:issue149

I have run `rebase -i` and `push -f` many times, and I will run them again and again, so these commits are in flux and for reference only.

**Comment by timholy** [comment]
You're a hero! FYI I have some more tests and implementation improvements to `ccolor` almost ready, but I'll wait until you've finished the reorg.
