### ISSUE TITLE
[RFC] Dropping support for non-RGB/Gray types in `rand`

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#150]
Probably the next release of Colors.jl will depend "tightly" on the next release of ColorTypes.jl. So, what about moving `rand` for color types to Colors.jl on this occasion?

cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/140

**Edit:**
ColorTypes v0.10 and Colors v0.12 were released without changing `rand`. I will leave this issue open for the time being.

**Comment by timholy** [comment]
Does anyone besides me feel a bit uncomfortable about supporting `rand` more broadly across color types? What bothers me is the sampling. For example, suppose you want to sample points inside the circle. You might think that the following two approaches would yield the same result:
```julia
julia> function rejection(n)
           pts = Tuple{Float64,Float64}[]
           while length(pts) < n
               x, y = 2*rand()-1, 2*rand()-1
               if x^2 + y^2 <= 1
                   push!(pts, (x, y))
               end
           end
           return pts
       end
rejection (generic function with 1 method)

julia> function polar(n)
           function randpolar()
               r, θ = rand(), 2π*rand()
               return (r*cos(θ), r*sin(θ))
           end
           return [randpolar() for i = 1:n]
       end
```
Yet if you generate 10^4 samples from each and plot the histogram of `x` values, you get this:
![hist](https://user-images.githubusercontent.com/1525481/72609404-6965bf80-38ea-11ea-96af-ff30f74340e9.png)

As a consequence, doing `rand(RGB{Float32}, n)` and then converting to HSV will lead to a different result than `rand(HSV{Float32}, n)`.

Perhaps we could just document this. But I thought I'd at least mention that it bothers me a bit.

**Comment by kimikage** [comment]
> As a consequence, doing `rand(RGB{Float32}, n)` and then converting to HSV will lead to a different result than `rand(HSV{Float32}, n)`.

I personally think that is obvious. In the first place, I think the problem is to use a uniform distribution without recognizing those differences. :confused:
If my feeling is far from many people, I have to be more careful to support the gamut. In general, the gamut is not a 2-D figure or 3-D cube, but a complex hull or a set of multiple hulls. I proposed using a bounding box to avoid that complexity (cf. #140). However, `rand` is dangerous because it is too easy to use.

**Comment by kimikage** [comment]
Like `Lab` and `LCHab`, Cartesian and cylindrical coordinate systems are interchangeable except for the pivots. So there is a problem with where to set the outer boundaries, but not with regard to sampling density.
However, `HSV` colorspace is often modeled as a cone rather than a cylinder (The similar things applies to `HSL` etc.). Therefore, there is ambiguity in the definition of sampling density.

**Comment by kimikage** [comment]
Although the behavior of `rand` is debatable, what I want to decide first is whether we support the gamuts in ColorTypes.jl. If we decide not to support gamuts in ColorTypes.jl, I will work on supporting the gamuts in Colors.jl.
I do not plan to implement color management features for the time being, but the gamut definitions can make the RGB <--> XYZ conversions more general.

Like the current "wrong" `gamutmax`/`gamutmin`, it is possible to support `rand` without using "native" gamuts. The problem is consistency and customizability.I don't want packages to overwrite functions of other packages instead of to enhance them. Dropping the support is helpful for the consistency.

**Comment by kimikage** [comment]
At least in the next ColorTypes v0.10, let's keep the status quo.  I think a little more discussion is needed.
However, I also think that there is no problem to fix "typos" (cf. #125).

**Comment by timholy** [comment]
I'm OK with keeping `rand` for other color types. We should just document that the distribution will be different.

**Comment by kimikage** [comment]
> If the main discussion is somewhere besides https://github.com/JuliaGraphics/ColorTypes.jl/issues/150, can you provide a link?

_Originally posted by @timholy in https://github.com/JuliaGraphics/Colors.jl/issues/379#issuecomment-593087411_

It is difficult to organize the issues related to the gamut because it is involved in various problems. The following are some of the links.

Background issue: https://github.com/JuliaGraphics/Colors.jl/issues/8
Directly related issue: https://github.com/JuliaGraphics/ColorTypes.jl/issues/125
My proposal issue (closed): https://github.com/JuliaGraphics/ColorTypes.jl/issues/139
My proposal PR (closed): https://github.com/JuliaGraphics/ColorTypes.jl/pull/140
Non-sRGB gamut issue: https://github.com/JuliaGraphics/Colors.jl/issues/372
Conversion matrices based on color primaries: https://github.com/JuliaGraphics/Colors.jl/issues/355#issuecomment-539524932

**Comment by timholy** [comment]
Thanks for the summary! Loosely speaking I would support the following:
- committing to the notion that `RGB` means `sRGB`
- applying gamma conversion/inversion where appropriate
- adding gamuts in cases where they can be reasonably specified. Should these be "bounding boxes" (all valid parameter combinations lie within the box) or "inscribed boxes" (all parameter combinations within the box are valid)?

But let me also say that I won't stand in the way of folks who have thought about this more than I have just making a decision.

**Comment by kimikage** [comment]
My other concern is that the current `rand` in ColorTypes.jl extends `rand` directly without using `Random` API (i.e. samplers).

I think it is not a fatal issue, since I use `rand` only for testing and benchmarking. However, perhaps, we may want to use RINGs other than the global RNG for image processing.

**Comment by timholy** [comment]
Yeah, that seems like a good idea. The Random interface has changed a lot over the years and this package hasn't kept up.

**Comment by kimikage** [comment]
I've been thinking that the `rand`s for rgbs (`<:AbstractRGB`) and grays (`<:AbstractGray`) should be implemented in ColorTypes. I'm sick of no one trying to fix those implementations and continuing to use ugly workarounds.:confused:
Should I update the `rand` just for rgbs and grays?

**Comment by timholy** [comment]
Can you clarify what you mean a bit more? What I'm confused about is that those rands are already in ColorTypes. Do you mean removing the support for other color spaces?

Or are you talking about the performance issues due to ReinterpretArray? On 1.6 it's already a lot better due to https://github.com/JuliaLang/julia/pull/37277. I'm planning this weekend to implement `reinterpret(reshape, T, a)` according to https://github.com/JuliaLang/julia/pull/37290#issuecomment-685020916 which should hopefully solve the main remaining cases. There's still the regression in inlining `fieldcount` (https://github.com/JuliaLang/julia/pull/37230, which is "dead" as a PR but "live" as an issue report), but once we have `reinterpret(reshape, T, a)` then we can work around it for the purposes of ColorTypes.

**Comment by kimikage** [comment]
> Do you mean removing the support for other color spaces?Do you mean removing the support for other color spaces?

Yes, that was the original intent, but I'm not really interested in that anymore.

I'm not referring to some specific problems, I'm just complaining that the current implementation is "outdated" in solving some specific problems.

Here's an example of a specific problem I saw today:
```julia
julia> rand(RGB24)
ERROR: TypeError: in Type{...} expression, expected UnionAll, got Type{RGB24}
Stacktrace:

julia> rand(ARGB32)
ERROR: TypeError: in Type{...} expression, expected UnionAll, got Type{ARGB32}
```

I've known about this problem for a long time, and I know it will work if I add the definitions below.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/bd31741d162361ebd44ed05ae532266998d9ce9f/src/operations.jl#L68-L71
Of course I don't like that solution. But if I try to fix the whole implementation, I have to deal with `gamutmax`/`gamutmin`, which I hate more. :sweat_smile:

**Comment by kimikage** [comment]
Incidentally, the other specific problem is the inefficient and incorrect handling of `FixedPoint`.
```julia
julia> rand(RGB{Q0f7})
RGB{Q0f7}(0.891Q0f7,-0.344Q0f7,0.938Q0f7)
```
What was the meaning of `gamutmin`? :joy:

Although `Q0f7` etc. cannot represent `1`, it doesn't matter because the floating point types are also within the range of [0, 1).

**Comment by kimikage** [comment]
In #221, I've added tests for the problem with `rand`, so I'll close this.
ColorTypes.jl will continue to support `rand` after v0.12.

**Comment by johnnychen94** [comment]
Thank you @kimikage for faithfully record all these changes (even if I don't have the expertise to track all of them)
