### ISSUE TITLE
Problem with `eltype(RGB)` or showing strange "RGB{Any}"

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#151]
See: https://github.com/JuliaGraphics/Colors.jl/issues/369

I guess that the direct solution for JuliaGraphics/Colors.jl#369 is enhancing `zeros` in ColorVectorSpace.jl. (Of course, *only for `Gray`*, doing that in ColorTypes.jl is another option.)

Well, in the first place, `Gray{Any}` and `RGB{Any}` look strange to me.
```julia
julia> using ColorTypes

julia> eltype(RGB)
Any

julia> eltype(AGray)
Any

julia> typeof(RGB)
UnionAll

julia> typeof(RGB{Float32})
DataType
```
Yes, this is a known issue.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/53c59257c3dddbebb05a899324a202a89d5ed213/test/runtests.jl#L27-L28

Of course, I don't really want to get `"Gray{<:Union{Bool, AbstractFloat, FixedPointNumbers.FixedPoint}}"` in the type summary. :smile:

Should we fix anything? Or will we continue to use `"Any"` for convenience?

**Comment by kimikage** [comment]
If we regard this as a display problem, perhaps we need to fix `colorant_string_with_eltype`.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/53c59257c3dddbebb05a899324a202a89d5ed213/src/traits.jl#L219-L234

BTW, I think that `colorant_string`, `colorant_string_with_eltype` and `showcoloranttype` should be in "show.jl " rather than "traits.jl", because they are not exported. `showcoloranttype` should definitely be moved to "show.jl".

**Comment by kimikage** [comment]
I don't like this recursive trick very much. Perhaps it was a necessary technique in older versions, though.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/53c59257c3dddbebb05a899324a202a89d5ed213/src/traits.jl#L111-L116

However, it will take some care to handle `UnionAll`s properly. For example:
https://github.com/JuliaGraphics/ColorTypes.jl/blob/53c59257c3dddbebb05a899324a202a89d5ed213/src/traits.jl#L148-L154

**Comment by timholy** [comment]
A lot of the type gymnastics could be simplified now---these constructs were necessary on earlier Julia versions, but modern Julia is much better at this kind of stuff. (In particular, `ccolor` is terrifying but should be much more straightforward now.) `eltype` could be
```julia
eltype(::Type{C}) where {C<:Colorant{T}} where {T} = T
eltype(::Type{C}) where {C<:Colorant} = Base.parameter_upper_bound(C, 1)
```
but because we use `Any` as a marker in other places we'd have to make several compensating changes.

**Comment by kimikage** [comment]
For now, which is the best for the "display" of `RGB` (array)?
- "RGB{Any}"
  - status quo, and wrong
- "RGB"
  - the simplest
- "RGB{Union{AbstractFloat,FixedPointNumbers.FixedPoint}}"
  - simple implementation, but still wrong
- "RGB{<:Union{AbstractFloat,FixedPointNumbers.FixedPoint}}"
- "RGB{<:Union{AbstractFloat,FixedPoint}}"
- "RGB{<:ColorTypes.Fractional}"
  - ad-hoc, but more readable
- "RGB{<:Fractional}"

Or should we switch the form according to the IO context?

**Comment by timholy** [comment]
Interesting question. Probably `RGB` makes most sense.

**Comment by kimikage** [comment]
Another strange example:
```julia
julia> TransparentColor{RGB{Float32},Float32,4}[]
0-element Array{TransparentColor{Float32},1} with eltype TransparentColor{RGB{Float32},Float32,4}
```

**Comment by kimikage** [comment]
`eltype(RGB)` still returns `Any`. If you want to fix this behavior, please submit a separate issue.
