### ISSUE TITLE
Finding the definition of RGBA

### ISSUE THREAD

**Issue by andrewcooke** [JuliaGraphics/ColorTypes.jl#16]
it's taken me a good 45 minutes to work out how RGBA is defined (a lot of that spent grepping other packages wondering what i was doing wrong because i didn't see it in ColorTypes).  maybe i shouldn't be doing that, or maybe i'm dumb, but i do worry that the code is "too clever".

i don't have a good solution for how you improve things, sorry.  but i felt i should flag this.  i've written similar code in my life and, in general, come to regret it when other people don't understand it.

**Comment by SimonDanisch** [comment]
I run into the same thing and am not too happy about it, either.
We should write out at least the types and exports.

**Comment by SimonDanisch** [comment]
I put it on my list at low priority. If you have some time feel free to prepare a PR.
Probably wait for @timholy's comment, since he wrote the code.
Best,
Simon

**Comment by timholy** [comment]
I'd be fine with a PR that did all this manually.

**Comment by andrewcooke** [comment]
yikes.  i am not going to do all that manually!  how about https://github.com/JuliaGraphics/ColorTypes.jl/pull/17 ?  it makes the names explicit, so that they can be found more easily.  one downside is that the explicit list needs to be maintained, so i added a tets.

**Comment by timholy** [comment]
Looks great, thanks!
