### ISSUE TITLE
Is it necessary to add alpha(x::Number)?

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#162]
In some cases, ColorTypes treats scalar numbers like grays.
```julia
julia> Gray(0.5) == 0.5
true
```
The existence of `gray(x::Number)` is another example of that.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/5b2e50d62b8fd47a860c2e0543446144d8627c87/src/traits.jl#L36

According to that idea, perhaps we need `alpha(x::Number)`:
```julia
alpha(x::Number) = alpha(Gray(x))
```
or
```julia
alpha(x::Number) = oneunit(x)
```

**Comment by kimikage** [comment]
BTW, `gray(x::Number)` is "loose".
```julia
julia> gray(Complex(0,1)) # The imaginary gray feels like a contemporary art theme.
0 + 1im

julia> Gray(Complex(0,1))
ERROR: StackOverflowError:
```
I believe `Real` is more realistic than `Number`.  However, `gray(x::Real)` still has problems.
```julia
julia> gray(1//2)
1//2

julia> Gray(1//2)
ERROR: MethodError: no method matching unsafe_trunc(::Type{UInt8}, ::Rational{Int64})
```

**Comment by kimikage** [comment]
This is also an off-topic, but if we modify these getter-like methods, it may be good idea to use `reinterpret` instead of the `N0f8`'s internal constructor.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/5b2e50d62b8fd47a860c2e0543446144d8627c87/src/traits.jl#L34-L35

**Comment by timholy** [comment]
I'm not certain that `gray(1//2)` is a problem. After all, it's "give me the real-valued number that this possibly-`Gray` object corresponds to." If it's `Gray(-2.3)`, it seems you want it to give you -2.3.

**Comment by kimikage** [comment]
I think the problem is that `gray()` returns values in "types" which `Gray` cannot handle. In this regard, `-2.3` is fine. `gray(1//2)` is a problem with the `Gray` constructor, not with `gray()`.

If scalar numbers are the essence of "grays" and `Gray` is just a subset of them, that's fine. I do not agree with that, though.:smile:

**Comment by timholy** [comment]
Fair enough. How about
```julia
gray(x::Real) = convert(eltype(ccolor(Gray, typeof(x))), x)
```

**Comment by kimikage** [comment]
I don't remember much about this :sweat_smile:, but the `alpha(::Number)` suggestion must come from some reasons or contexts. The development of ColorTypes v0.10 started from the issue #144.

The reason why I talk about the context is that I noticed the current PR #177 adds some tests but doesn't fix any broken tests. It's wired. In other words, I think some tests have been missing.

Maybe...
```julia
julia> RGB(0.8)
RGB{Float64}(0.8,0.8,0.8)

julia> ARGB32(0.8)
ARGB32(0.8N0f8,0.8N0f8,0.8N0f8,1.0N0f8)

julia> ARGB(0.8)
ERROR: MethodError: no method matching alpha(::Float64)
```

**Comment by timholy** [comment]
> PR #177 adds some tests but doesn't fix any broken tests

Isn't it because it's becoming more stringent? We didn't have tests for "I'm not stringent" because the lack of stringency wasn't a design goal as much as a consequence of the implementation. Now that we're thinking through behavior more carefully things are becoming more stringent. The package was not written to the practices of TDD, I'm afraid, as revealed by the fact that the test suite started small and has grown over time.

**Comment by kimikage** [comment]
Oh, I found the origin.:smile: https://github.com/JuliaGraphics/ColorTypes.jl/pull/161#discussion_r379263557
