### ISSUE TITLE
Problems with RGB24/ARGB32 conversions

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#163]
PR #158 revealed the following conversion problems:
```julia
julia> convert(AbstractARGB{RGB,N0f8}, RGB24(), 0.2)
ERROR: No conversion of (RGB24(0.0N0f8,0.0N0f8,0.0N0f8),alpha=0.2) to ARGB{Normed{UInt8,8}} with consistency-types RGB and RGB24 has been defined

julia> convert(ARGB32, RGB(), 0.2)
ERROR: No conversion of (RGB{N0f8}(0.0,0.0,0.0),alpha=0.2) to ARGB32 with consistency-types RGB24 and RGB has been defined

julia> convert(ARGB, RGB24(), 0.2)
ERROR: No conversion of (RGB24(0.0N0f8,0.0N0f8,0.0N0f8),alpha=0.2) to ARGB{Normed{UInt8,8}} with consistency-types RGB and RGB24 has been defined
```
PR #161 is going to fix some conversion problems, but the problems above may be not fixed.
These conversions are (re-)implemented in Colors.jl. I want to clarify the division of functionality with ColorTypes.jl in the next version of Colors.jl.

There are two minor problems:
```julia
julia> real(Gray(0.6))
0.6

julia> real(Gray24(0.6))
ERROR: MethodError: no method matching real(::Gray24)
```
```julia
julia> convert(AGray32, 0.6, 0.2)
AGray32{N0f8}(0.6,0.2)

julia> convert(ARGB32, 0.6, 0.2)
ERROR: MethodError: no method matching convert(::Type{ARGB32}, ::Float64, ::Float64)
```

I'm ready to fix this issue. I will send PR after merging PR #161 and fixing issue #129.

**Comment by kimikage** [comment]
BTW, in the fixes for this issue, I'm going to move `reinterpret` to " conversions.jl".
Since no one has done https://github.com/JuliaGraphics/ColorTypes.jl/issues/63#issuecomment-259394834 for more than three years, is it unnecessary? If so, is it due to a performance problem with `ReinterpretArray`?

**Comment by timholy** [comment]
Those are separate issues, as defining that `reinterpret` method bypasses `ReinterpretArray`. We could define `ReinterpretWrapper` for scalars that uses the same techniques as ReinterpretArray, but no one has gotten around to it. And the performance of `ReinterpretArray` is such that it's probably better to special-case anyway.

**Comment by kimikage** [comment]
I don't think #63 is important, but I also don't think it is good to leave #63 open. As a matter of fact, the snippet of OP is no longer useful.
However, it is off-topic.
