### ISSUE TITLE
example of generic (RGB) code

### ISSUE THREAD

**Issue by goretkin** [JuliaGraphics/ColorTypes.jl#166]
I'm not sure if this is a correct example (I'm not sure if this operation is defined only on `TransparentRGB`, or for any `TransparentColor`), but it could be a concrete example to elaborate how to write generic code using this package.

```julia
"""
straight alpha to premultiplied alpha
# https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied
"""
function sa_to_pma(c::T) where {T<:TransparentColor}
  T(
    ((red(c), green(c), blue(c)) .* alpha(c))...,
    alpha(c))
end
```

**Comment by timholy** [comment]
You're implicitly assuming AbstractRGB, so to be a good teaching example you'd have to fix that. Moreover, consider using `base_color_type` and the two-arg constructor.

If we do decide to store some examples, do you have a suggestion where to put them?

**Comment by kimikage** [comment]
In any case, this is a bit more than an application (e.g. image processing).
