### ISSUE TITLE
Further improvements of `color_types` and so on

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#168]
Sorry, I made some mistakes in PR #158. :sob: For example:
https://github.com/JuliaGraphics/ColorTypes.jl/blob/6ea2fa082f3cafd49c7d83f4eecf8a64314ee259/test/traits.jl#L237
https://github.com/JuliaGraphics/ColorTypes.jl/blob/6ea2fa082f3cafd49c7d83f4eecf8a64314ee259/test/traits.jl#L290-L292
I'm ashamed so I want to fix them.

The `color_type`, `base_color_type` and `base_colorant_type` have been really improved by @timholy (cf. PR #161).:tada:
I didn't notice at all during the review, but there might be room for further improvement.
```julia
julia> color_type(Colorant)
ERROR: MethodError: no method matching color_type(::Type{Colorant})

julia> base_color_type(Colorant) # base_color_type calls color_type
ERROR: MethodError: no method matching color_type(::Type{Colorant})

julia> base_colorant_type(Colorant{T,3} where T) # base_colorant_type works fine with Colorant,
Colorant{T,3} where T

julia> base_colorant_type(AlphaColor) #  but there is a problem with dispatching
TransparentColor

julia> base_color_type(AlphaColor) # On the other hand, base_color_type works fine with AlphaColor/ColorAlpha
Color
```
I don't think there are many opportunities to use abstract types in these methods, but the fixes will help improve the promotion rules.

Also, for consistency, I think it is better to add support for `Number` to `color_type` and `base_colorant_type`, now. (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/152#issuecomment-57599760)

**Comment by timholy** [comment]
Good call. As you've noted, it's extremely difficult to figure out how these should behave.
