### ISSUE TITLE
Support for 4-component color types

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#179]
There has been a request for `CMYK` support for some time (cf. https://github.com/JuliaGraphics/Colors.jl/issues/264).
IMO, Colors.jl, Images.jl and so on still need some time to properly handle the `CMYK` colors, so we should not add `CMYK` to ColorTypes *for now*.

However, it is good that users can easily define and use 4-component (or 2-component) colors.

It is good to specialize the 3-component or 1-component colors in terms of performance, but at present, they are also specialized in terms of functionalities, i.e. they lack generality.
For example, 4-component colors cannot be shown properly.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/8afb1507c4a3e1f77dd7131ea5771963be5e6cc3/src/show.jl#L9-L12

**Comment by kimikage** [comment]
Why doesn't `throw_colorerror`(and its caller `checkval`) use the color types directly?
https://github.com/JuliaGraphics/ColorTypes.jl/blob/4bb8aa9c918c376a14c2717c4e9edef67224f94c/src/types.jl#L683-L695

**Comment by kimikage** [comment]
Anyway, in order to handle types like `ACMYK{N0f8}`, we need to add a 5-arg `checkval`.
Since Julia doesn't seem to do "horizontal" SIMD optimizations, I think there is room for optimizations.
https://github.com/JuliaGraphics/ColorTypes.jl/blob/4bb8aa9c918c376a14c2717c4e9edef67224f94c/src/types.jl#L644-L652

**Comment by timholy** [comment]
> Why doesn't throw_colorerror(and its caller checkval) use the color types directly?

Clearly it should!

**Comment by johnnychen94** [comment]
> IMO, Colors.jl, Images.jl and so on still need some time to properly handle the CMYK colors, so we should not add CMYK to ColorTypes for now.

I don't quite get the reason behind, could you please give some further explanation on this?

**Comment by kimikage** [comment]
In the first place, Colors.jl does not have "practical" conversion methods between CMYK space and other color spaces. I think that CMYK conversion which is not based on color profiles is just a toy. :smile:

> Do you mean adding CMYK to ColorTypes doesn't make it generally a valid input to functions in Colors and Images because it has 4 components?

At least I don't think that has been fully tested. It is quite possible that there are codes other than the above which interpret the 4-component colors as `RGBA` or `Transparent3` colors. Moreover, `TransparentCMYK` is a 5-component color.

In order to run such tests, it is important that ColorTypes.jl handles 2-/4-/5-component colors correctly first.

**Comment by kimikage** [comment]
Tests for `show`.
```julia
using ColorTypes, FixedPointNumbers

# dummy type for testing 2-component color
struct AnaglyphColor{T} <: Color{T,2} # not `TransparentGray`
    left::T; right::T
end
# dummy type for testing 4-component color
struct CMYK{T} <: Color{T,4} # not `Transparent3`
    c::T; m::T; y::T; k::T
end
# dummy type for testing 5-component color
struct ACMYK{T} <: AlphaColor{CMYK{T},T,5}
    alpha::T; c::T; m::T; y::T; k::T
    ACMYK{T}(c, m, y, k, alpha=1) where T = new{T}(alpha, c, m, y, k)
end

iob = IOBuffer()
```
```julia
julia> show(iob, AnaglyphColor{Float32}(0.4, 0.2));

julia> String(take!(iob))
"AnaglyphColor{Float32}(0.4f0,1.0f0)"

julia> ans == "AnaglyphColor{Float32}(0.4f0,0.2f0)"
false

julia> show(iob, CMYK{Float64}(0.1, 0.2, 0.3, 0.4));

julia> String(take!(iob))
"CMYK{Float64}(0.1,0.2,0.3,1.0)"

julia> ans == "CMYK{Float64}(0.1,0.2,0.3,0.4)"
false

julia> show(iob, ACMYK{N0f8}(0.2, 0.4, 0.6, 0.8));
ERROR: MethodError: no method matching show_normed(::Base.GenericIOBuffer{Array{UInt8,1}}, ::ACMYK{Normed{UInt8,8}})

julia> String(take!(iob))
""

julia> ans == "ACMYK{N0f8}(0.2,0.4,0.6,0.8,1.0)"
false
```

**Comment by kimikage** [comment]
This is off-topic but... what is this!? :scream:
https://github.com/JuliaGraphics/ColorTypes.jl/blob/4bb8aa9c918c376a14c2717c4e9edef67224f94c/test/show.jl#L44

**Comment by kimikage** [comment]
Although there are some problems with promotion rules etc., the original goal was almost achieved.
