### ISSUE TITLE
readme update: "FloatingPoint" -> "AbstractFloat"

### ISSUE THREAD

**Issue by ablaom** [JuliaGraphics/ColorTypes.jl#185]
I think `FloatingPoint` is the obsolete abstract type now called `AbstractFloat`, yes? This confused me for a while.

**Comment by timholy** [comment]
Thanks for the report! Fixed in #188. Also note that you can submit fixes by clicking on the pencil icon (someone will have to approve your changes, so don't worry about messing up).
