### ISSUE TITLE
register_error_hint not defined.

### ISSUE THREAD

**Issue by chriselrod** [JuliaGraphics/ColorTypes.jl#192]
On Julia master 1.5.0-DEV.823, [this line](https://github.com/JuliaGraphics/ColorTypes.jl/blob/23cae4e94a4189fbd41ed8688a2280c691d6d8e7/src/error_hints.jl#L4) should probably read `Base.Experimental.register_error_hint`.

**Comment by kimikage** [comment]
cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/186#discussion_r418357506
