### ISSUE TITLE
Add const before types

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaGraphics/ColorTypes.jl#195]
I find a lot type alias do not have const before it. Like here
https://github.com/JuliaGraphics/ColorTypes.jl/blob/18f51286da039b9ec30cc0b0b0f36dce14497c7d/src/types.jl#L68

This can cause type instability (at least before Julia1.0, it is so), and will have performance issue.

Is it supposed to be fixed?

**Comment by kimikage** [comment]
cf. https://github.com/JuliaGraphics/ColorTypes.jl/pull/146#issuecomment-573129399

BTW, current ColorTypes no longer supports Julia v0.x.

**Comment by GiggleLiu** [comment]
Thanks. If Tim says so, it should be true. Close.
