### ISSUE TITLE
[RFC] let colorant type constructor accept colorant type as input

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/ColorTypes.jl#201]
## Colorant instance

To deal with numbers and pixels (colorant instance), the usage is unified; the left and right column has the same pattern.

| | `x = 1.0N0f8` |  `c = Gray(1.0N0f8)` |
| --- | --- | --- |
| preserve color type & N0f8->float | `float(x)` | `float(c)` |
| preserve color type & float->N0f8 | `n0f8(x)` | `n0f8(c)` |
| change color type & preserve storage type | `RGB(x)` | `RGB(x)` |
| change color type & N0f8->float | `RGB(float(x))` | `RGB(float(c))` |
| change color type & float->N0f8 | `RGB(n0f8(x))` | `RGB(n0f8(x))` |

## Colorant type

However, it is not the case if we're processing colorant types.

The left column in the following table doesn't follow the same pattern as the right column:

| | `T = N0f8` | `C = Gray{N0f8}` |
| --- | --- | --- |
| preserve color type & N0f8->float | `float(T)` | `float(C)` |
| preserve color type & float->N0f8 | `n0f8(T)` | `n0f8(C)` |
| change color type & preserve storage type | `RGB{T}` | `RGB{eltype(C)}` |
| change color type & N0f8->float | `RGB{floattype(T)}` | `RGB{floattype(eltype(C))}` |

---

To unify how we deal with number types and colorant types, I'm proposing to let `Gray(C) == Gray{eltype(C)}`.

With this, the table shapes to:

| | `T = N0f8` | `C = Gray{N0f8}` |
| --- | --- | --- |
| preserve color type & N0f8->float | `float(T)` | `float(C)` |
| preserve color type & float->N0f8 | `n0f8(T)` | `n0f8(C)` |
| change color type & preserve storage type | `RGB(T)` | `RGB(C)` |
| change color type & N0f8->float | `RGB(float(T))` | `RGB(float(C))` |

The equivelance`RGB(float(T)) == float(RGB(T))` holds.

I feel a lot pleased noting the similarity of how we processing instances and types.

---

I know this doesn't follow the convention that type constructor should return an instance of that.  For me, this won't be that severe since the input is also a type.

**Comment by kimikage** [comment]
I don't know what specific problems will be solved by this change. As you know, I don't think this is the functionality which should be realized by the constructors. We have the special function `ccolor`.

**Comment by johnnychen94** [comment]
> I don't know what specific problems will be solved by this change.

To share the same code while supporting both Number types and Colorant types.

> We have the special function ccolor.

Makes sense, I didn't realize that this already works out-of-box; I didn't see much of this usage in the codebase of JuliaImages and thought this a missing functionality.

The table with `ccolor` is:

| | `T = N0f8` | `C = Gray{N0f8}` |
| --- | --- | --- |
| preserve color type & N0f8->float | `float(T)` | `float(C)` |
| preserve color type & float->N0f8 | `n0f8(T)` | `n0f8(C)` |
| change color type & preserve storage type | `ccolor(RGB, T)` | `ccolor(RGB, C)` |
| change color type & N0f8->float | `ccolor(RGB, float(T))` | `ccolor(RGB, float(C))` |

**Comment by kimikage** [comment]
Although `color` has been around for a long time, "gray-like real" was supported from the current v0.10. (PR #161)
