### ISSUE TITLE
[RFC] Simplified display of colors and arrays of colors

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#202]
This is similar to issue #191, but for non-gray types.

If we think of colors as containers for numbers, the following is also reasonable and consistent with `Array`:
(current)`"RGB{Float32}(1.0f0,0.5f0,0.0f0)"`-->(proposed)`"RGB{Float32}(1.0,0.5,0.0)"`

In fact, `Normed` colors have that kind of special handling.
```julia
julia> RGB{N0f8}(1,0.5,0)
RGB{N0f8}(1.0,0.502,0.0)
```
Of course, the following are completely different in implementation, but I think that the second style has no problem in "display".
```julia
RGB{Float32}[RGB{Float32}(1.0f0,0.5f0,0.0f0)] # fully specified (current)

RGB{Float32}[RGB(1.0,0.5,0.0)]                # via RGB{Float64} (proposed)

RGB{Float32}[RGB{Float32}(1.0,0.5,0.0)]       # without :typeinfo handling

RGB{Float32}[RGB(1.0f0,0.5f0,0.0f0)]          # bottom-up and top-down are confusing
```

**Comment by johnnychen94** [comment]
If the colorant constructor accepts tuple as input, then we may get an even concise display:

```julia
RGB{Float32}[(1.0,0.5,0.0)] # if RGB((1.0, 0.5, 0.0)) works
```

**Comment by kimikage** [comment]
I was thinking the same thing.
Perhaps in order for the color constructors to accept `Tuple` inputs, the color to `Tuple` conversions should be implement first.(cf. https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/131#discussion_r443177446) That is, we have to make a strict distinction between a sequence of constructor arguments (i.e. something like `Vararg`) and a tuple representation of a color.

In any case, we should report separate issues.

**Comment by johnnychen94** [comment]
> That is, we have to make a strict distinction between a sequence of constructor arguments (i.e. something like Vararg) and a tuple representation of a color.

I'm not sure if I get your concerns clearly; are there any conceptual differences between `RGB(1.0, 0.5, 0.0)` and `RGB((1.0, 0.5, 0.0))`, or will it introduce any ambiguity here?

**Comment by kimikage** [comment]
I think the conceptual difference is essentially the first case of https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-vs.-Construction-1.

Perhaps we have to follow the import rule in https://github.com/JuliaGraphics/ColorTypes.jl/pull/184#issuecomment-644138321. However, we (can) have a bit looser definitions of the constructors. For example:
```julia
julia> RGB( RGBA(0,0,0,1) ) # this is a "conversion" case
RGB{N0f8}(0.0,0.0,0.0)
```
In other words, we should follow the important rule, so the users don't have to be aware of the difference.
