### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/ColorTypes.jl#225]
rand: Error During Test at D:\a\ColorTypes.jl\ColorTypes.jl\test\operations.jl:61
 Unexpected Pass
 Expression: all(all_in_range, rand(ARGB{Q3f12}, 1))
 Got correct result, please change to @test if no longer broken.

From https://github.com/JuliaGraphics/ColorTypes.jl/pull/224/checks?check_run_id=1869979411

**Comment by kimikage** [comment]
I'm sorry. I had initially intended to generate 10 random colors. I must have rewritten it during the experiment and forgot to put it back.
```julia
all(all_in_range, rand(ARGB{Q3f12}, 10))
```
`2^-40` is a sufficiently small probability that it is less than the probability of my typo. :joy: If you are unsure, let's make it 1000. :smile:

**Comment by timholy** [comment]
No worries, and a failure rate that is smaller than the number of, say, PRs in Julia's history is not something I'd worry about :smile:.
