### ISSUE TITLE
[RFC] Warn about the normalization first in error messages of RGB constructors

### ISSUE THREAD

**Issue by kimikage** [JuliaGraphics/ColorTypes.jl#242]
I have recently seen a misuse like `RGB(255, 0.0, 0.0)`.
It is inconceivable that such a misuse could happen without any context. If I were to speculate on the user's actions, the user would have written something like `RGB(255, 0, 0)` first. Then, the following error message should have been displayed.
```julia
julia> RGB(255, 0, 0)
ERROR: ArgumentError: (255, 0, 0) are integers in the range 0-255, but integer inputs are encoded with the N0f8
  type, an 8-bit type representing 256 discrete values between 0 and 1.
  Consider dividing your input values by 255, for example: RGB{N0f8}(255/255,0/255,0/255)
  Or use `reinterpret(N0f8, x)` if `x` is a `UInt8`.
  See the READMEs for FixedPointNumbers and ColorTypes for more information.
```
I think that error message is more than kind enough. However, maybe some users will stop reading in the middle of the first sentence.
The first sentence indirectly mentions the normalization, but it can also be interpreted as a restriction on the specific encoding of `N0f8`. Then, there may be an incentive to use types other than `N0f8` or integers. The trouble is, that is not exactly wrong.

I think it would be better to first mention the normalization as a common rule of `AbstractRGB`, then give an example of `RGB{N0f8}(255/255, 0/255, 0/255)`, and finally explain `N0f8`.

It might be a good idea to color the example to make it stand out.

**Comment by johnnychen94** [comment]
@ashwani-rathee We might also want to emphasize this bit of stuff in juliaimages' documentation. Someplace in https://juliaimages.org/stable/tutorials/quickstart/#The-0-to-1-intensity-scale I think.

**Comment by kimikage** [comment]
Another additional option is to add a hint about `colorant"rgb(255,0,0)"` in Colors.jl. However, it is not possible to determine whether the arguments are constant or not in error handling.
