### ISSUE TITLE
`init` keyword for `reducec` and `mapreducec`

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/ColorTypes.jl#247]
The current API is not consistent with `reduce`/`mapreduce`.

```diff
- reducec(op, v0, c)
+ reducec(op, c; init=zero(eltype(eltype(c))))

- mapreducec(f, op, v0, c)
+ mapreducec(f, op, c; init=zero(eltype(eltype(c)))
```

Maybe, we can just make `mapc`/`reducec`/`mapreducec` as Colorant methods of `map`/`reduce`/`mapreduce`?

**Comment by kimikage** [comment]
I agree with the support of the keyword argument `init`. However, there is room for debate about compatibility.
If we support multiple input colors, (as the current `mapc` supports,) there will be some confusion. For example:
```julia
mapreducec((a, b) -> max(a, b), *, Gray(1), Gray(0)) # Does `Gray(1)` mean the `v0`?
```
I don't think this is much of a problem in the current situation. However, issue #207 needs to be considered more carefully.
If the current formats are to be deprecated, we need to prepare for `depwarn`.

BTW, this isn't an essential issue, but the default value of `init` seems to depend on the operator `op`.
```julia
julia> mapreduce(identity, +, (1.0, 0.5, 0.25))
1.75

julia> mapreduce(identity, +, (1.0, 0.5, 0.25), init=0)
1.75

julia> mapreduce(identity, *, (1.0, 0.5, 0.25))
0.125

julia> mapreduce(identity, *, (1.0, 0.5, 0.25), init=1)
0.125
```

**Comment by kimikage** [comment]
I also set one of the milestones for v0.13 to be the provision of iterator interfaces (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/131#issuecomment-824544538)
In that case, `reducec` and `mapreducec` may not be necessary anymore.
```julia
julia> components(c::Color3) = (comp1(c), comp2(c), comp3(c)); # substitute a tuple for an iterator object

julia> mapreduce(identity, *, components(RGB(1.0, 0.5, 0.25)))
0.125

julia> mapreducec(identity, *, 1.0, RGB(1.0, 0.5, 0.25))
0.125

```

**Comment by kimikage** [comment]
Even if we may deprecate `reducec` and `mapreducec` in the future, I think it would be beneficial to change their implementation to `reduce`/`mapreduce`-based (unless there is a significant performance degradation).

The ability to omit the initial value is more attractive than the ability to explicitly specify the `init` keyword argument.
