### ISSUE TITLE
Excessive precompilation causes long package load time

### ISSUE THREAD

**Issue by KristofferC** [JuliaGraphics/ColorTypes.jl#269]
This package does an almost combinatorial amount of precompilation. This causes the package to be slow enough to load that one has to think a second time if it is worth adding it as a dependency. At the same time, this package is described as "minimalistic" which doesn't really jive with a 0.3 second load time:

```jl
julia> @time using ColorTypes
  0.297764 seconds (672.76 k allocations: 51.498 MiB, 7.03% gc time, 4.14% compilation time)
```

Removing the precompilation takes it down quite a bit:

```jl
julia> @time using ColorTypes
  0.128889 seconds (277.90 k allocations: 17.985 MiB, 6.22% gc time, 8.33% compilation time)
```

As a reference, we can compare this to loading the whole package manager (of course not using the one in the sysimage):

```jl
julia> @time using Pkg
  0.154056 seconds (258.31 k allocations: 17.384 MiB, 6.85% gc time, 51.36% compilation time)
```

So the minimalistic package for holding some color types takes twice the time to load as the Julia package manager.

This is unfortunate because I presume a lot of people (like me) want to use the package just to hold values of some type but don't really do any computations with them.

Could the amount of precompilation be reduced, or alternatively, could there be an actual minimalistic ColorTypes package that is very quick to load?

**Comment by johnnychen94** [comment]
Sounds reasonable enough for me, I'd like to hear what @timholy and @kimikage (if he is still around) think.

**Comment by timholy** [comment]
Sure, we can do this. Once https://github.com/JuliaLang/julia/pull/42016 works, it won't be necessary to stash these in this package.

**Comment by KristofferC** [comment]
I don't think this package needs much explicit precompilation. In 1.8 people should get the methods they use (transitively) anyway from their own precompilation scripts.
