### ISSUE TITLE
ColorTypes v0.11.1 is perhaps too breaking

### ISSUE THREAD

**Issue by johnnychen94** [JuliaGraphics/ColorTypes.jl#273]
This new version breaks the test for ImageCore, ImageIO, ImageQualityIndexes, and perhaps more...

I'm currently occupied with other stuff so don't have time to find out what's really breaking, so how about reverting all those changes, tag a new v0.11.2 release to override the breaking v0.11.1 version.
Then we can tag a 0.12 release so that we have more time to gradually upgrade it?

issue list:

- #275 
- #277 
- https://github.com/JuliaImages/ImageCore.jl/pull/181

**Comment by johnnychen94** [comment]
update: #276 and #278 fixes the test in ImageIO and ImageQualityIndexes

**Comment by timholy** [comment]
Copied from elsewhere: 

Oh shoot. I didn't check how much was on master, big mistake.

I will try to fix this. I think the best plan is to fork a release 0.11 branch, backport my recent commit, and release 0.11.2. Reasonable?

**Comment by timholy** [comment]
Fair to say this was closed by #280?
