### ISSUE TITLE
B&W color type?

### ISSUE THREAD

**Issue by bjarthur** [JuliaGraphics/ColorTypes.jl#29]
would it make sense to add a black and white color type?  something like:

```
immutable BW <: AbstractGray{Bool}
    val::Bool
end
```

my use case is that i have an image stored as an `Array{Bool,2}`.  to convert it to an `Image` i have to:

```
convert(Image{Gray},convert(Array{UFixed8},img_cmos_red_thresh))
```

would be nice if i could simply:

```
convert(Image{BW},img_cmos_red_thresh)
```

and have everything in Images work.

**Comment by timholy** [comment]
Does `grayim(A)` not work on its own?

I can see a reason that you'd want to make it a `Gray{Bool}`; currently that's not supported, but it could be. The fix would be in the ColorTypes package.

**Comment by bjarthur** [comment]
`grayim` on an `Array{Bool}` throws an error when the output is used with `Images.save`:

```
julia> img=rand(Bool,4,5)
4x5 Array{Bool,2}:
  true   true  false  false  true
 false  false  false   true  true
 false   true  false  false  true
  true  false  false   true  true

julia> grayim(img)
Binary Images.Image with:
  data: 4x5 Array{Bool,2}
  properties:
    colorspace: Gray
    spatialorder:  x y

julia> convert(Image{Gray},convert(Array{UFixed8},img))
Gray Images.Image with:
  data: 4x5 Array{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt8,8}},2}
  properties:
    timedim: 0
    spatialorder:  y x
    pixelspacing:  1.0 1.0

julia> Images.save("foo.jpg",grayim(img))
WARNING: MethodError(ImageMagick.mapinfo,(
Binary Images.Image with:
  data: 4x5 Array{Bool,2}
  properties:
    colorspace: Gray
    spatialorder:  x y,))
 in save_ at /Users/arthurb/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
 in save at /Users/arthurb/.julia/v0.4/ImageMagick/src/ImageMagick.jl:64
 in save at /Users/arthurb/.julia/v0.4/FileIO/src/loadsave.jl:92
 in save at /Users/arthurb/.julia/v0.4/FileIO/src/loadsave.jl:51
ERROR: MethodError: `mapinfo` has no method matching mapinfo(::Images.Image{Bool,2,Array{Bool,2}})

julia> Images.save("foo.jpg",convert(Image{Gray},convert(Array{UFixed8},img)))
```

**Comment by timholy** [comment]
See https://github.com/JuliaIO/ImageMagick.jl/pull/27 for the `save` issue.

> The fix would be in the ColorTypes package.

Very perceptive comment of me, since this is the ColorTypes package :smile:.

If you'd like to add your `BW` type (or perhaps `Gray{Bool}`), I'd support that.

**Comment by timholy** [comment]
Just as an update, `Gray` now supports `Bool` as an eltype: https://github.com/JuliaGraphics/ColorTypes.jl/blob/3fedf2023a39ec92114868a48c740f9273a2ba08/src/types.jl#L344
