### ISSUE TITLE
InvertedGray needed for TIFF MINISWHITE

### ISSUE THREAD

**Issue by mkitti** [JuliaGraphics/ColorTypes.jl#295]
I'm considering an `InvertedGray <: AbstractGray` type that has the intepretation that lower values correspond to white.

I encountered this need in https://github.com/tlnagy/TiffImages.jl/pull/134

**Comment by mkitti** [comment]
Further thought: perhaps a general `Inverted` type would be a good idea

**Comment by tlnagy** [comment]
I would support adding a general `Inverted{T}` type, but are there any examples of inverted RGB, etc? I haven't seen such a thing.

**Comment by mkitti** [comment]
I believe there is a general concept of inverting a RGB value.

https://pinetools.com/invert-color

Also we already have `ColorVectorSpace.complement`. 

```
julia> using ColorVectorSpace

julia> complement(Gray(1))
Gray{N0f8}(0.0)

julia> complement(RGB(0.75, 0.25, 0))
RGB{Float64}(0.25,0.75,1.0)
```

Maybe this should be called `Complement{T}` and be a lazy version of `complement`?

**Comment by mkitti** [comment]
Now I'm wondering if we're at the wrong package. Maybe this should also be in ColorVectorSpace.jl?

**Comment by tlnagy** [comment]
Honestly @timholy or @johnnychen94 would know better than me, but a lazy `complement` might be a general solution to this.

**Comment by timholy** [comment]
Yeah, given that `complement` is in ColorVectorSpace, let's add a `Complement{T,N,C<:Colorant{T,N}}} <: Colorant{T,N}` there. It's a bit of a pity that we can't just call this `Complement{C}` and preserve the subtyping, but perhaps there's some clever typealiasing that could be done?

**Comment by mkitti** [comment]
Prototype is here:
https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/189

**Comment by kimikage** [comment]
A practical case, where inverted representations other than Gray are used is CMYK.
However, *I am* against implementing `CMYK` in `ColorTypes.jl`. (cf. https://github.com/JuliaGraphics/ColorTypes.jl/issues/179#issuecomment-616886589)

(Note that CMYK in TIFF is not a situation where `Complement` is needed, since TIFF recommends mapping `255` as 100% ink coverage.)

**Comment by mkitti** [comment]
Closing xref: https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/189#issuecomment-2198438118
