### ISSUE TITLE
Support more `==` operations

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/ColorTypes.jl#36]
We might want to define `==` operators for more `ColorTypes`. Observe:
```jl
julia> using Colors

julia> RGB{U8}(1,0,0) == RGB{Float32}(1,0,0)
true

julia> YCbCr{Float64}(1,0,0) == YCbCr{Float32}(1,0,0)
false

julia> @which RGB{U8}(1,0,0) == RGB{Float32}(1,0,0)
==(c1::ColorTypes.AbstractRGB, c2::ColorTypes.AbstractRGB) at /home/tim/.julia/v0.5/ColorTypes/src/traits.jl:250
```
CC @mronian, noticed in https://github.com/timholy/Images.jl/pull/458#discussion_r65613527.

**Comment by mronian** [comment]
I'll add to the existing ones. Should this be moved to ColorVectorSpace?

**Comment by timholy** [comment]
No, it should be done here. As long as two colors have the same "base" colorant type, then you should be able to compare them independent of differences in the element type.

Comparisons with conversion to different color spaces is more of a `Colors` thing, since that package handles conversions among color spaces.

ColorVectorSpace is only about math with colors, basically defining things that don't actually make sense from a colorimetry perspective but which are useful nonetheless in many applications.

**Comment by mronian** [comment]
Got it :)
