### ISSUE TITLE
Error converting from RGB{U8} to HSL

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaGraphics/ColorTypes.jl#40]
If I have:
```julia
convert(HSL, RGB{U8}(0.678, 0.847, 0.902))
```
I get
```
ERROR: InexactError()
 in trunc at float.jl:374
```
I am not entirely sure what the code paths for this conversion are. But is this expected? I get this kind of error once in a blue moon when doing similar kinds of conversions.

**Comment by timholy** [comment]
Thanks for reporting this; it's always helpful to have concrete examples of failures, so we can make them rarer.

Conversions among different colorspaces are handled by `Colors.jl`, see https://github.com/JuliaGraphics/Colors.jl/pull/249.
