### ISSUE TITLE
How to construct Transparent color from name + alpha?

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/ColorTypes.jl#43]
I'd like to get a TransparentColor by name and adding the alpha.
```
julia> alphacolor(colorant"red2")
ARGB{U8}(0.933,0.0,0.0,1.0)

julia> alphacolor(colorant"red2",0.6)
ERROR: MethodError: no method matching alphacolor(::ColorTypes.RGB{FixedPointNumbers.UFixed{UInt8,8}}, ::Float64)
Closest candidates are:
  alphacolor{C<:ColorTypes.Color{T,N}}(::C<:ColorTypes.Color{T,N}) at /home/lobi/.julia/v0.5/ColorTypes/src/conversions.jl:59
```

**Comment by timholy** [comment]
Seems reasonable. You could just add the appropriate defs [here](https://github.com/JuliaGraphics/ColorTypes.jl/blob/1a9563fa0f1c804527eabb4a9c5dc6c96412b7c2/src/conversions.jl#L59-L62).

**Comment by lobingera** [comment]
Thank you, i was just wondering, if i missed something.

**Comment by timholy** [comment]
Want to make a PR out of it?

**Comment by lobingera** [comment]
Sure. But it's top of my list...

**Comment by Evizero** [comment]
While implementing this I found some curiosity by accident. should `alphacolor(RGB24)` be undefined? To naive me it would seem sensible if it were to return `ARGB32`, which I could add [here](https://github.com/JuliaGraphics/ColorTypes.jl/blob/master/src/types.jl#L481-L482)

**Comment by lobingera** [comment]
Btw i meant it's not top of my list, but my smart phone has own ideas how to spend my time...

**Comment by Evizero** [comment]
@lobingera I figured.

**Comment by timholy** [comment]
>  should `alphacolor(RGB24)` ... return `ARGB32`?

That seems like a good idea.
