### ISSUE TITLE
BigFloat breaks == on `GrayA` and `AGray`

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaGraphics/ColorTypes.jl#52]
supprisingly the following comparisons do not work.
```julia
julia> AGray{BigFloat}(0.5,0.25) == AGray{BigFloat}(0.5,0.25)
false
julia> GrayA{BigFloat}(0.5,0.25) == GrayA{BigFloat}(0.5,0.25)
false
```
In both cases the comparison should return true.

**Comment by SimonDanisch** [comment]
Ha! Thats a funny one. `AGray` is an immutable so it's compared by value... But in this case I'm guessing that the value is the pointer to the `BigFloat` ;)

**Comment by SimonDanisch** [comment]
( I guess not that funny to run into :(  )... And I'm kind of wrong in a sense.
It seems there is a method missing for the AGray case:
https://github.com/JuliaGraphics/ColorTypes.jl/blob/master/src/traits.jl#L274

**Comment by hofmannmartin** [comment]
Just tested for the other ColorTypes and the same problem occurs for `RGBA`, `BGRA`, `ABGR`, `ARGB` if `BigFloat` is the element type.

**Comment by SimonDanisch** [comment]
https://github.com/JuliaGraphics/ColorTypes.jl/pull/53
