### ISSUE TITLE
Move reinterpret (& separate?) from Images?

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/ColorTypes.jl#6]
This package is intended to be quite minimalistic, so it's not clear that we should add more functions. But I wonder whether `reinterpret(Float32, A::Array{RGB{Float32}})` should be moved here? (It "unpacks" an array of `Color`s into the underlying raw numbers at essentially zero-cost.) It's implemented in Images.jl. One might even consider moving `separate` too. Or are these better off in Images? Images deals with arrays; there is nothing here (yet) dealing with arrays.

Thoughts?

**Comment by lobingera** [comment]
If i read correctly, Colors. jl is the place for conversions.

**Comment by timholy** [comment]
It is, except for conversions that don't change the colorspace. For example,
```
c = RGB{U8}(1,0.5,0)
convert(RGB{Float32}, c)
```
is handled here. `reinterpret` is even simpler, in that all it does is change the type of the object without changing the bytes in memory.

That said, I'm leaning away from moving that functionality here, and leaving it in Images.
