### ISSUE TITLE
reinterpret problem

### ISSUE THREAD

**Issue by bjarthur** [JuliaGraphics/ColorTypes.jl#63]
`reinterpret` works for vector but not scalar `Gray{Float64}`.  it claims it's not a bitstype for the latter.  to debug, i made a fake `type Bar`, meant to mimic the definition of `Gray`, for which `reinterpret` works for neither scalar or vector.  could someone please give me a hint as how to fix this?  i do not see any applicable `reinterpret` methods in all of `ColorTypes.jl`.  thanks.

```
julia> using ColorTypes

julia> reinterpret(Gray{Float64},rand(Float64,3),(3,))
3-element Array{ColorTypes.Gray{Float64},1}:
 Gray{Float64}(0.807567) 
 Gray{Float64}(0.528818) 
 Gray{Float64}(0.0608983)

julia> reinterpret(Gray{Float64},rand(Float64))
ERROR: reinterpret: target type not a leaf bitstype
 in reinterpret(::Type{ColorTypes.Gray{Float64}}, ::Float64) at ./essentials.jl:86

julia> type Bar{T<:AbstractFloat}
              x::T
              end

julia> reinterpret(Bar{Float64},rand(Float64,3),(3,))
ERROR: ArgumentError: cannot reinterpret Array{Float64} to ::Type{Array{Bar{Float64}}}, type Bar{Float64} is not a bitstype
 in reinterpret(::Type{Bar{Float64}}, ::Array{Float64,1}, ::Tuple{Int64}) at ./array.jl:87

julia> reinterpret(Bar{Float64},rand(Float64))
ERROR: reinterpret: target type not a leaf bitstype
 in reinterpret(::Type{Bar{Float64}}, ::Float64) at ./essentials.jl:86
```

**Comment by timholy** [comment]
`Bar` has to be an immutable.

The error just comes from the default `reinterpret` fallback. There's nothing wrong with defining
```jl
reinterpret{T}(::Type{Gray{T}}, x::T) = Gray(x)
```

**Comment by bjarthur** [comment]
thanks for the help @timholy .

i'm inclined to think however that this is a bug in `Base`.  the `box` function that `reinterpret` calls for scalars differs in it's behavior to `Gray{Float64}` than the `jl_reshape_array` function that `reinterpret` calls for vectors.  see the simple hack below of passing in a vector of length one as a work around, and the different method that is called as a result.

so, instead of hacking `ColorTypes` with your suggested additional `reinterpret` method, wouldn't it be better to fix `Base`, if indeed my thinking is correct that this is where the bug lies?

```
julia> using ColorTypes

julia> reinterpret(Gray{Float64},rand(Float64))
ERROR: reinterpret: target type not a leaf bitstype
 in reinterpret(::Type{ColorTypes.Gray{Float64}}, ::Float64) at ./essentials.jl:86

julia> reinterpret(Gray{Float64},rand(Float64,1))
1-element Array{ColorTypes.Gray{Float64},1}:
 Gray{Float64}(0.795983)

julia> @which reinterpret(Gray{Float64},rand(Float64))
reinterpret{T}(::Type{T}, x) at essentials.jl:86

julia> @which reinterpret(Gray{Float64},rand(Float64,1))
reinterpret{T,S}(::Type{T}, a::Array{S,1}) at array.jl:73
```

**Comment by SimonDanisch** [comment]
I think I've run into this very long ago... Funny, that the error is still the same, misleading one.
Here we go: https://github.com/JuliaLang/julia/issues/10140

**Comment by timholy** [comment]
I'll leave this open in case anyone wants to contribute the reinterpret methods exemplified in https://github.com/JuliaGraphics/ColorTypes.jl/issues/63#issuecomment-259394834

**Comment by kimikage** [comment]
Since there seems to be little demand for `reinterpret` for non-array objects, I will close this once.
