### ISSUE TITLE
Binary Images

### ISSUE THREAD

**Issue by Cody-G** [JuliaGraphics/ColorTypes.jl#76]
I'm interested in viewing binary images, and my first thought was doing so via `colorview(Gray, img)` where `img` is a boolean array.  This throws the following error:

```
julia> ImagePlayer.imshow(colorview(Gray,msk))
ERROR: MethodError: no method matching isfinite(::ColorTypes.Gray{Bool})
Closest candidates are:
  isfinite(::Float16) at float16.jl:119
  isfinite(::BigFloat) at mpfr.jl:799
  isfinite(::DataArrays.NAtype) at /home/cody/.julia/v0.5/DataArrays/src/predicates.jl:10
  ...
 in znan at /home/cody/.julia/v0.5/ImagePlayer/src/ImagePlayer.jl:459 [inlined]
 in mapreduce_impl(::ImagePlayer.#znan, ::Base.#scalarmin, ::Array{ColorTypes.Gray{Bool},2}, ::Int64, ::Int64) at ./reduce.jl:270
 in _mapreduce(::ImagePlayer.#znan, ::Base.#scalarmin, ::Base.LinearFast, ::Array{ColorTypes.Gray{Bool},2}) at ./reduce.jl:162
 in minfinite(::Array{ColorTypes.Gray{Bool},2}) at /home/cody/.julia/v0.5/ImagePlayer/src/ImagePlayer.jl:461
 in #initialize_canvas#3(::Void, ::Void, ::Array{Any,1}, ::Function, ::Gtk.GtkAspectFrameLeaf, ::Array{ColorTypes.Gray{Bool},4}) at /home/cody/.julia/v0.5/ImagePlayer/src/ImagePlayer.jl:98
 in #imshow#2(::String, ::Array{Any,1}, ::Function, ::Array{ColorTypes.Gray{Bool},4}) at /home/cody/.julia/v0.5/ImagePlayer/src/ImagePlayer.jl:75
 in imshow(::Array{ColorTypes.Gray{Bool},4}) at /home/cody/.julia/v0.5/ImagePlayer/src/ImagePlayer.jl:44
```
I can fix this by adding this method in the ColorVectorSpace package:

`isfinite{T<:Bool}(c::ColorTypes.AbstractGray{T}) = isfinite(gray(c))`

I'm happy to submit that as a pull request if it's an adequate solution.  I also wondered if it might be better to implement a Binary type in `ColorTypes` because binary images really aren't gray.  What do people think?

**Comment by bjarthur** [comment]
i'm all for a black and white colortype!  see https://github.com/JuliaGraphics/ColorTypes.jl/issues/29

**Comment by lobingera** [comment]
Just as idea: indexColor -> map from integernumber via a list of Colors to Image?

**Comment by timholy** [comment]
`Gray{Bool}` (which is now supported in ColorTypes) isn't entirely a misnomer, since grayscale images include the colors black and white. Would `typealias BW Gray{Bool}` be satisfying? It's a little scarier to not call it gray since there's a lot of other code you'd have to update for something that's not in the `AbstractGray` hierarchy.

> Just as idea: indexColor -> map from integernumber via a list of Colors to Image?

I'm not sure I understand your point, @lobingera (did you mean to post that in a different thread?), but see [IndirectArrays](https://github.com/JuliaArrays/IndirectArrays.jl).

**Comment by timholy** [comment]
Also, just plain-old `Bool` seems to work too.

**Comment by Cody-G** [comment]
I'm certainly okay with binary images using the Gray type.  In that case it's still necessary to define `isfinitie` to get `colorview(Gray, img)` to work as I demonstrated in my first post.  Should I submit a PR with the added `isfinite` definition?  I suppose the definition could be even simpler really:

`isfinite{T<:Bool}(c::ColorTypes.AbstractGray{T}) = true`

**Comment by Evizero** [comment]
Just as a clarification. `colorview(Gray, bool_array)` itself seems to work perfectly fine for me. So the whole `isfinite` issue seems to be triggered by `ImagePlayer.imshow`

**Comment by timholy** [comment]
Yes, a PR would be great!

**Comment by Cody-G** [comment]
@Evizero yes you are right, my mistake!  I still think it makes more sense to update `ColorVectorSpace` than to update `ImagePlayer`, so I will submit a PR over there.

**Comment by timholy** [comment]
Seems like nothing needs doing here.
