### ISSUE TITLE
rem is ambiguous error

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/ColorTypes.jl#79]
Noticed this error starting to appear on Travis nightly.

`ERROR: LoadError: LoadError: MethodError: rem(::Int64, ::Type{FixedPointNumbers.Normed{UInt8,8}}) is ambiguous. Candidates:
  rem(x::Real, ::Type{T}) where T<:FixedPointNumbers.Normed in FixedPointNumbers at /home/vagrant/.julia/v0.6/FixedPointNumbers/src/normed.jl:59
  rem(x::Integer, T::Type) in Base at int.jl:375
Stacktrace:
 [1] ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}}(::Int64, ::Int64, ::Int64) at /home/vagrant/.julia/v0.6/ColorTypes/src/types.jl:91
 [2] ColorTypes.RGB(::Int64, ::Int64, ::Int64) at /home/vagrant/.julia/v0.6/ColorTypes/src/types.jl:445
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:539
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/vagrant/.julia/v0.6/Colors/src/algorithms.jl, in expression starting on line 66
while loading /home/vagrant/.julia/v0.6/Colors/src/Colors.jl, in expression starting on line 35
`

Do I need to change anything, or will this go away eventually?

Related perhaps are these warnings that appeared yesterday in a Documenter-generated docs build on version 0.5?

`
WARNING: Method definition mapc(Any, Number) in module ColorTypes at /Users/travis/.julia/v0.5/ColorTypes/src/operations.jl:104 overwritten in module ImageCore at /Users/travis/.julia/v0.5/ImageCore/src/map.jl:110.
WARNING: Method definition mapc(Any, Number) in module ColorTypes at /Users/travis/.julia/v0.5/ColorTypes/src/operations.jl:104 overwritten in module ImageCore at /Users/travis/.julia/v0.5/ImageCore/src/map.jl:110.
`

**Comment by Evizero** [comment]
xref https://github.com/JuliaMath/FixedPointNumbers.jl/pull/81

**Comment by cormullion** [comment]
@Evizero Thanks! Tim's way ahead of me... :)

**Comment by tkelman** [comment]
also fixed in base, but would be nice to avoid with a base test of some kind if possible, given how many failures it caused
