### ISSUE TITLE
Check gamut during construction

### ISSUE THREAD

**Issue by oxinabox** [JuliaGraphics/ColorTypes.jl#83]
It would be nice if the inputs to the constructor were checked to lay within the valid range given by the gamut.
Then throw up either an error, or a warning that could be suppressed with a flag to the constructor.

Many of the Gamut ranges are given by traits already:
https://github.com/JuliaGraphics/ColorTypes.jl/blob/d23a8abc2c04cf9ec90bd38fff18bbf9b2e74ada/src/operations.jl#L7

I know I often find myself with HSVs that are slightly outside the gamut because I've messed something up.
And I endup finding out because after i've converted them to RGBs, the plotting package I am using throws up an error.

It would also be nice for the gamut to be specified in the docstring for each type.
Can that be done dynamically with string interning?
I have also made the mistake of thinking that HSV hue was in radians, or that hue was also a 0.0:1.0 range.

**Comment by timholy** [comment]
If we do this, how do you propose we compute `mean(img::Array{<:RGB})` efficiently? The gamut of RGB is 0-1 in all components, and since `mean(img)` is implemented as `sum(img)/length(img)`, we'll run out of dynamic range in a hurry.

**Comment by oxinabox** [comment]
A fair point.

If the warning approach was taken then we would add an overload here, that suppresses warnings, in the sum operation.

Or it could be calculated out of type, in a normal array.

**Comment by timholy** [comment]
It's not just `sum`, it's a whole heck of a lot of operations. Can't you just define `checked_HSV`?

**Comment by timholy** [comment]
Since we have `N0f8` to enforce the gamut of RGB, I think we can close this.
